<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 8</p>

We will use the titanic dataset from Kaggle (https://www.kaggle.com/). This is a well-known dataset and we will use it for classification- if the passenger survived or passed away.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
training_DF = pd.read_csv('titanic_dataset_GBC.csv')

In [3]:
training_DF['Age'].fillna(training_DF['Age'].mean(), inplace=True)

In [4]:
training_DF.drop('Cabin',axis=1,inplace=True)

In [5]:
training_DF.dropna(inplace=True)

In [6]:
sex = pd.get_dummies(training_DF['Sex'])
embark = pd.get_dummies(training_DF['Embarked'])

In [7]:
training_DF.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

In [8]:
training_DF = pd.concat([training_DF,sex,embark],axis=1)

In [9]:
training_DF.drop(['female','C'],axis=1,inplace=True)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(training_DF.drop('Survived',axis=1), 
                                                    training_DF['Survived'], test_size=0.30, 
                                                    random_state=101)

In [12]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

In [14]:
# let's explore SGDClassifier parameters

# loss: hinge, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))


# Let's form SGD models with variation in paameters loss and alpha
    # loss: 'hinge', 'log', and 'modified_huber'
    # alpha: 0.0001 and 0.001
    # explain and dicuss your findings

[[ 44 119]
 [ 29  75]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [15]:
# loss: log, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='log',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))

[[162   1]
 [101   3]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [16]:
# loss: modified_huber, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))

[[ 42 121]
 [ 28  76]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [17]:
# loss: hinge, alpha: 0.001
sdg_model = SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))

[[161   2]
 [ 99   5]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [18]:
# loss: hinge, alpha: 0.001
sdg_model = SGDClassifier(
    loss='log',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))

[[125  38]
 [ 61  43]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [19]:
# loss: hinge, alpha: 0.001
sdg_model = SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,sdg_prediction))

[[ 26 137]
 [ 13  91]]


/Users/wanghanlun/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
